import Cocoa

class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ notification: Notification) {
        // Register for the 'getURL' event (GURL = 1196711500)
        NSAppleEventManager.shared().setEventHandler(
            self,
            andSelector: #selector(handleGetURLEvent(_:withReplyEvent:)),
            forEventClass: AEEventClass(1196711500),
            andEventID: AEEventID(1196711500)
        )
    }
    
    @objc func handleGetURLEvent(_ event: NSAppleEventDescriptor, withReplyEvent replyEvent: NSAppleEventDescriptor) {
        // keyDirectObject = 757935405
        guard let urlString = event.paramDescriptor(forKeyword: AEKeyword(757935405))?.stringValue else {
            NSLog("MatchaMail: Failed to extract URL from event")
            return
        }

        let matchaPath = "{{MATCHA_PATH}}"
        
        // Create a temporary .command file. macOS automatically opens these in Terminal.
        let tempDir = NSTemporaryDirectory()
        let commandFileUrl = URL(fileURLWithPath: tempDir).appendingPathComponent("matcha-open.command")
        
        let scriptContent = """
        #!/bin/bash
        # This script was generated by MatchaMail handler
        '\(matchaPath)' '\(urlString)'
        # Remove ourselves after execution
        rm -- "$0"
        """
        
        do {
            try scriptContent.write(to: commandFileUrl, atomically: true, encoding: .utf8)
            
            // Make the file executable
            let attributes = [FileAttributeKey.posixPermissions: 0o755]
            try FileManager.default.setAttributes(attributes, ofItemAtPath: commandFileUrl.path)
            
            // Open the file with the default handler (which is Terminal.app for .command files)
            NSWorkspace.shared.open(commandFileUrl)
            NSLog("MatchaMail: Successfully launched Terminal with command file")
            
        } catch {
            NSLog("MatchaMail: Error creating or opening command file: \(error.localizedDescription)")
        }

        // Exit quickly
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            NSApp.terminate(nil)
        }
    }
}

let delegate = AppDelegate()
NSApplication.shared.delegate = delegate
NSApplication.shared.run()
